### ISSUE TITLE
Investigate migration to VitePress

### ISSUE THREAD

**Issue by zoey-kaiser** [sidebase/docs#174]
### Describe the feature

As Docus is now abandoned (https://github.com/nuxt-themes/docus/issues/1016), we will not receive any updates or security patches for our documentation software. 

Therefore, we want to look into migrating to [vitepress](https://vitepress.dev/). For this, we need to estimate how long it will take and what the benefits would be, to decide if it makes sense!

**Comment by brenoepics** [comment]
I've been taking a look at the repo, it would be necessary to change the routes, the md files are mostly ok besides some alert syntax... just the blog and some other things that needs changes to make components in a way that looks good on Vitepress, the server part apparently isn't used as it only has this [healthcheck](https://github.com/sidebase/docs/blob/main/server/api/health.ts)

also, I can help with vp migration.

**Comment by zoey-kaiser** [comment]
Hi @brenoepics 👋 

Thanks for doing an initial investigation! I think the main migration of the documentation should be fairly straightforward, as you pointed out! Do you know how easy it would be to migrate the [LandingPage ](https://github.com/sidebase/docs/blob/main/layouts/Landing.vue)of the documentation? 

The difficulties I still see are:
- Migrate the landing page
- Redesigning the landing page to be more inline with the style of Vitpress
- Figure out versioning of the documentation to allow us to continue splitting the docs of major releases of the modules

Feel free to continue the investigation, however for now, we are prioritizing some updates on the modules themselves and would potentially revisit the documentation migration in the summer!
