### ISSUE TITLE
Fix incomplete sentence in `nuxt-auth` docu

### ISSUE THREAD

**Issue by LukSteib** [sidebase/docs#35]
### Describe the bug

* 2nd paragraph of `nuxt-auth` > `Introduction` ends with an incomplete sentence (see [link](https://sidebase.io/nuxt-auth/getting-started) and screenshot below)

screenshot of paragraph
<img width="650" alt="image" src="https://user-images.githubusercontent.com/36229155/206675634-74ddbcc0-a386-4120-b5fc-7dd8b2c67c7d.png">

**Comment by BracketJohn** [comment]
Good catch ❤️
