### ISSUE TITLE
Sidebar is broken on mobile

### ISSUE THREAD

**Issue by BracketJohn** [sidebase/docs#59]
### Environment

https://sidebase.io/

### Describe the bug

sidebar only shows blog on mobile:
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/25911230/208411972-a156f037-d3c4-4edf-8f1f-f05c093e82da.png">

**Comment by zoey-kaiser** [comment]
Due to upgrade of Docus to v1.1.10.

See changes here: 
https://github.com/nuxt-themes/docus/pull/710#issuecomment-1341770910
